dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$CI_REGISTRY_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin
      - docker build -t travis-ci-build-stages-demo services/client
      - docker images
      - docker tag travis-ci-build-stages-demo $CI_REGISTRY_USER/travis-ci-build-stages-demo
      - docker push $CI_REGISTRY_USER/travis-ci-build-stages-demo
    - stage: test
      script: docker run --rm $CI_REGISTRY_USER/travis-ci-build-stages-demo ls
    - script: docker run --rm $CI_REGISTRY_USER/travis-ci-build-stages-demo ls