dist: trusty

env:
  - IMAGE: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME

jobs:
  include:
    - stage: build
      name: "Build users"
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - echo "$IMAGE"
        - docker pull $IMAGE:users || true